{% set name = "snakeviz" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92ad876fb6a201a7e23a6b85ea96d9643a51e285667c253a8653643804f7cb68

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - snakeviz = snakeviz.cli:main
  number: 0

requirements:
  build:
    - pip
    - python >=3.6
    - setuptools
    - tornado >=2.0
  run:
    - python >=3.6
    - tornado >=2.0

test:
  commands:
    - snakeviz -h
  imports:
    - snakeviz

about:
  home: https://jiffyclub.github.io/snakeviz/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: An in-browser Python profile viewer
  description: |
    SnakeViz is a viewer for Python profiling data that runs as a web application in your browser.
  doc_url: https://jiffyclub.github.io/snakeviz
  dev_url: https://github.com/jiffyclub/snakeviz

extra:
  recipe-maintainers:
    - gforsyth
    - stanmart
